AppBundle\Entity\ContactForm:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactFormRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '40'
        surname:
            type: string
            length: '40'
        phone:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        message:
            type: string
            length: '400'
        postDate:
            type: datetime
        userIP:
            type: string
            length: 255
    lifecycleCallbacks: {  }
